name = "Teams"
uuid = "fff7cc20-6caa-4697-a237-1a4e44512a63"
authors = ["Conrad Wiebe"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
